import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Biotoolhub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen h-full relative flex flex-col">
          <Header />
          <main className="grid grid-cols-1 md:grid-cols-4">
            <div className="hidden md:flex">
              <Sidebar />
            </div>
            <div className="col-span-3">{children}</div>
          </main>
        </main>
      </body>
    </html>
  );
}
